AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  (SO8141)
  rewrite-url

  The Lambda@Edge is designed to rewrite host for custom origin
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Tags:
      Publisher: AWS

Metadata:
  AWS::ServerlessRepo::Application:
    Name: rewrite-url
    Description: The Lambda@Edge is designed to rewrite host for custom origin
    Author: AWS
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['gcr','gcr-solutions','cloudfront','cloudfront+','aws-cloudfront-extensions','edge','lambda-edge', 'aws']
    HomePageUrl: https://www.amazonaws.cn/en/solutions/lambda-edge-collection-for-cloudfront/
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/awslabs/aws-cloudfront-extensions/tree/main/edge/nodejs/rewrite-url

Parameters:
  UrlToRewrite:
    Type: String
    Default: "{}"
    Description: "Url mapping, for example: {\"www.example.com\": \"www.test.com\", \"www.demo.com\": \"www.test.net\"}"

Resources:
  RewriteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rewrite-url/
      Handler: app.handler
      Runtime: nodejs16.x
      Role: !GetAtt EdgeFunctionRole.Arn

  EdgeFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  UpdateEdgeCodeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn: RewriteFunction
    Properties:
      CodeUri: 's3://aws-cloudfront-extension-lambda-edge/update-lambda-function.zip'
      Handler: index.handler
      Runtime: python3.7
      Policies:
        - Statement:
          - Sid: RewritePolicy 
            Effect: Allow
            Action:
            - lambda:UpdateFunction*
            Resource: !GetAtt RewriteFunction.Arn

  UpdateConfigCustom:
    Type: Custom::UpdateConfigCustom
    DependsOn: UpdateEdgeCodeFunction
    Properties:
      ServiceToken: !GetAtt UpdateEdgeCodeFunction.Arn
      SourceUrl: 'https://aws-cloudfront-extension-lambda-edge.s3.amazonaws.com/edge/rewrite-url/rewrite-url.zip'
      EdgeFunctionArn: !GetAtt RewriteFunction.Arn
      HandlerFileName: 'app.js'       
      INPUT_URL_MAPPING: !Ref UrlToRewrite

Outputs:
  RewriteUrlFunction:
    Description: "Lambda Edge function ARN"
    Value: !GetAtt RewriteFunction.Arn
  RewriteUrlFunctionIamRole:
    Description: "Implicit IAM Role created for RewriteUrl function"
    Value: !GetAtt EdgeFunctionRole.Arn
  SolutionId:
    Description: "Solution id"
    Value: "SO8141"