AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'simple-lambda-edge

  Sample SAM Template for simple-lambda-edge

  '
Globals:
  Function:
    Timeout: 30
    Tags:
      Publisher: GCR-Solutions
Metadata:
  AWS::ServerlessRepo::Application:
    Name: simple-lambda-edge
    Description: Sample SAM Template for simple-lambda-edge
    Author: GCR Solutions
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://mingtong-sar-helloworld/34400b68072d710fecd0a2940a0d1658
    ReadmeUrl: s3://mingtong-sar-helloworld/725cb2db2cdd07f572d3532c3b6bc6a7
    Labels:
    - gcr
    - gcr-solutions
    - cloudfront
    - cloudfront+
    - aws-cloudfront-extensions
    - edge
    - lambda-edge
    - aws
    HomePageUrl: https://www.amazonaws.cn/en/solutions/
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/cc4i/aws-cloudfront-extensions/edge/python/simple-lambda-edge
Resources:
  SimpleLambdaEdgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mingtong-sar-helloworld/86c28b5affec727bbd5ad02d737739b8
      Handler: app.lambda_handler
      Runtime: python3.7
      Role:
        Fn::GetAtt:
        - EdgeFunctionRole
        - Arn
  EdgeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-edgeFunction
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
Outputs:
  SimpleLambdaEdgeFunction:
    Description: Simple Lambda Edge function ARN
    Value:
      Fn::GetAtt:
      - SimpleLambdaEdgeFunction
      - Arn
  SimpleLambdaEdgeFunctionIamRole:
    Description: Implicit IAM Role created for Simple Lambda Edge function
    Value:
      Fn::GetAtt:
      - EdgeFunctionRole
      - Arn
