version: 0.2

phases:
  install:
    commands:
      - n 17.9.0
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - npm install -g aws-cdk
      - cdk --version
  build:
    commands:
      # - cd templates/aws-cloudfront-monitoring/deployment/
      # - ./build-s3-dist.sh ${DIST_OUTPUT_BUCKET} ${SOLUTION_NAME} ${VERSION}
      - cd edge/cdk/deployment
      - ./build-s3-dist.sh ${DIST_OUTPUT_BUCKET} ${SOLUTION_NAME} ${VERSION}
  post_build:
    commands:
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml buildspec.yml || true
artifacts:
  files:
    - .git/**/*
    - deployment/**/*
    - docs/**/*
    - templates/aws-cloudfront-monitoring/deployment/**/*
    - buildspec.yml
    - CHANGELOG.md
    - .cfnnagignore
    - .cfnnag_*
