version: 0.2

phases:
  install:
    commands:
      - n 18
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
#      - git clone https://github.com/awslabs/aws-cloudfront-extensions.git /tmp/repo
#      - rsync -av /tmp/repo/ ${CODEBUILD_SRC_DIR}/ --exclude=buildspec.yml
      - npm install -g aws-cdk
      - cdk --version
      - git config --global user.email "cloudfront-extns-helper@example.com"
      - git config --global user.name "cloudfront-extns-helper"
      - VERSION=2.0.0
      - |-
        if [ $(git tag -l "$VERSION") ]; then
          git tag -d 2.0.0
        fi
#      - git clone https://github.com/awslabs/aws-cloudfront-extensions.git /tmp/repo
#      - rsync -av /tmp/repo/ ${CODEBUILD_SRC_DIR}/ --exclude=buildspec.yml
  build:
    commands:
      # - cd templates/aws-cloudfront-waf/deployment/
      # - ./build-s3-dist.sh ${DIST_OUTPUT_BUCKET} ${SOLUTION_NAME} ${VERSION}
      - cd templates/console/deployment/
      - chmod +x ./build-s3-dist.sh && ./build-s3-dist.sh ${DIST_OUTPUT_BUCKET} ${SOLUTION_NAME} ${VERSION}
  post_build:
    commands:
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml buildspec_2.yml || true
      - git tag -a 2.0.0 -m "${BUILD_NUMBER} ${CODEBUILD_RESOLVED_SOURCE_VERSION}"
artifacts:
  files:
    -