AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: '(SO8101)  multiple-origin-IP-retry

  The domain name of the customer''s origin site has multiple IPs. When the first
  IP fails to access, it needs to poll other IPs until the return to the source is
  successful, or all IPs fail after polling.

  '
Globals:
  Function:
    Timeout: 30
    Tags:
      Publisher: GCR-Solutions
Metadata:
  AWS::ServerlessRepo::Application:
    Name: multiple-origin-IP-retry
    Description: SAM Template for multiple-origin-IP-retry
    Author: GCR Solutions
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://minggu-sam-bucket-cloudfront/34400b68072d710fecd0a2940a0d1658
    ReadmeUrl: s3://minggu-sam-bucket-cloudfront/c9ca6ecd480d9afa8e2285226f4ef591
    Labels:
    - gcr
    - gcr-solutions
    - cloudfront
    - cloudfront+
    - aws-cloudfront-extensions
    - edge
    - lambda-edge
    - aws
    HomePageUrl: https://www.amazonaws.cn/en/solutions/
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/awslabs/aws-cloudfront-extensions/edge/nodejs/multiple-origin-IP-retry
Parameters:
  OriginIPList:
    Type: String
    Default: ''
    Description: Origin IP list for retry, use semicolon to separate multiple IP addresses
  OriginProtocol:
    Type: String
    Default: ''
    Description: Origin protocol, https or http
Resources:
  MultipleOriginIPRetry:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://minggu-sam-bucket-cloudfront/00dd0945b9ec28055d33ab0837b5e2b7
      Handler: app.handler
      Runtime: nodejs12.x
      Role:
        Fn::GetAtt:
        - EdgeFunctionRole
        - Arn
  EdgeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-edgeFunction
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      - arn:aws:iam::aws:policy/AWSLambdaFullAccess
  UpdateEdgeCodeFunction:
    Type: AWS::Serverless::Function
    DependsOn: MultipleOriginIPRetry
    Properties:
      CodeUri: s3://aws-cloudfront-extension-lambda-edge/update-lambda-function.zip
      Handler: index.handler
      Runtime: python3.7
      Role:
        Fn::GetAtt:
        - EdgeFunctionRole
        - Arn
  UpdateConfigCustom:
    Type: Custom::UpdateConfigCustom
    DependsOn: UpdateEdgeCodeFunction
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - UpdateEdgeCodeFunction
        - Arn
      SourceUrl: https://aws-cloudfront-extension-lambda-edge.s3.amazonaws.com/edge/multiple-origin-IP-retry/multiple-origin-IP-retry.zip
      EdgeFunctionArn:
        Fn::GetAtt:
        - MultipleOriginIPRetry
        - Arn
      HandlerFileName: app.js
      PARA_ORIGINIPLIST:
        Ref: OriginIPList
      PARA_ORIGINPROTOCOL:
        Ref: OriginProtocol
Outputs:
  MultipleOriginIPRetry:
    Description: Lambda Edge function ARN
    Value:
      Fn::GetAtt:
      - MultipleOriginIPRetry
      - Arn
  MultipleOriginIPRetryIamRole:
    Description: Implicit IAM Role created for Simple Lambda Edge function
    Value:
      Fn::GetAtt:
      - EdgeFunctionRole
      - Arn
  SolutionId:
    Description: Solution id
    Value: SO8101
