version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ygojnc4q90ir"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "OriginIPList=\"3.88.167.137;52.73.214.30\" DesktopPathParameter=\"dddd\" MobilePathParameter=\"eeee\" TabletPathParameter=\"rrr\" SmartTVPathParameter=\"ttt\""
