version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "log-rt"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14ykh8jrcjfzn"
s3_prefix = "log-rt"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = true
