Description: (SO8137) cross-origin-resource-sharing is a CloudFront Function which will add CORS(Cross Origin Resource Sharing) Headers
  
Resources:
  CORSFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: cross-origin-resource-sharing
      AutoPublish: true
      FunctionConfig:
        Comment: cross-origin-resource-sharing
        Runtime: cloudfront-js-1.0
      FunctionCode: |
        function handler(event) {
            var response = event.response;
            var headers = response.headers;

            headers['access-control-allow-origin'] = {value: '*'};
            headers['access-control-allow-headers'] = {value: 'Content-Type'};
            headers['access-control-allow-methods'] = {value: 'OPTIONS,POST,GET'};

            return response;
        }


Outputs:
  SolutionId:
    Description: "Solution id"
    Value: "SO8137"
