Description: (SO8142) add-cache-control-header is a CloudFront Function which adds a Cache-Control header for the browser so that content can be cached locally in the browser
  
Resources:
  AddCacheControlFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: add-cache-control-header
      AutoPublish: true
      FunctionConfig:
        Comment: add-cache-control-header
        Runtime: cloudfront-js-1.0
      FunctionCode: |
        function handler(event) {
            var response = event.response;
            var headers = response.headers;

            // Set the cache-control header
            headers['cache-control'] = {value: 'public, max-age=63072000'};

            // Return response to viewers
            return response;
        }


Outputs:
  SolutionId:
    Description: "Solution id"
    Value: "SO8142"
