AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "(SO8141) modify-host-origin-request-header is a lambda@Edge which shows how to modify the Host origin request header."

Globals:
  Function:
    Timeout: 5
    Tags:
      Publisher: AWS

Metadata:
  AWS::ServerlessRepo::Application:
    Name: modify-host-origin-request-header
    Description: The Lambda@Edge will modify the Host origin request header
    Author: AWS
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['gcr','gcr-solutions','cloudfront','cloudfront+','aws-cloudfront-extensions','edge','lambda-edge', 'aws']
    HomePageUrl: https://www.amazonaws.cn/en/solutions/lambda-edge-collection-for-cloudfront/
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/awslabs/aws-cloudfront-extensions/tree/main/edge/python/modify-host-origin-request-header

Parameters:
  originDomain:
    Default: ""
    Description: Domain for origin
    Type: String

Resources:
  ModifyRequestHeaderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: modify_host_origin_request_header/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt EdgeFunctionRole.Arn

  EdgeFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Sub ${AWS::StackName}-edgeFunction
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  UpdateEdgeCodeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn: ModifyRequestHeaderFunction
    Properties:
      CodeUri: 's3://aws-cloudfront-extension-lambda-edge/update-lambda-function.zip'
      Handler: index.handler
      Runtime: python3.7
      Role: !GetAtt EdgeFunctionRole.Arn

  UpdateConfigCustom:
    Type: Custom::UpdateConfigCustom
    DependsOn: UpdateEdgeCodeFunction
    Properties:
      ServiceToken: !GetAtt UpdateEdgeCodeFunction.Arn
      SourceUrl: 'https://aws-cloudfront-extension-lambda-edge.s3.amazonaws.com/edge/modify-host-origin-request-header/modify-host-origin-request-header.zip'
      EdgeFunctionArn: !GetAtt ModifyRequestHeaderFunction.Arn
      HandlerFileName: 'app.py'
      ORIGIN_DOMAIN: !Ref originDomain

Outputs:
  ModifyRequestHeaderFunctionARN:
    Description: "ARN"
    Value: !GetAtt ModifyRequestHeaderFunction.Arn
  SolutionId:
    Description: "Solution id"
    Value: "SO8141"
  ModifyRequestHeaderFunctionIamRole:
    Description: "Implicit IAM Role created for modify-response-status-code function"
    Value: !GetAtt EdgeFunctionRole.Arn
