AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  (SO8150)
  rt-log-transformer

  This Lambda will add custom content(eg. country code, isp) into the real-time CloudFront logs, it can add partition keys as well

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Tags:
      Publisher: AWS

Metadata:
  AWS::ServerlessRepo::Application:
    Name: rt-log-transformer
    Description: This Lambda will add custom content(eg. country code, isp) into the real-time CloudFront logs, it can add partition keys as well
    Author: AWS
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: [ 'gcr','gcr-solutions','cloudfront','cloudfront+','aws-cloudfront-extensions','edge','lambda-edge', 'aws' ]
    HomePageUrl: https://www.amazonaws.cn/en/solutions/amazon-cloudfront-extensions/
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/awslabs/aws-cloudfront-extensions/tree/main/edge/python/rt_log_transformer

Resources:
  TransformerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rt_log_transformer/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt TransformerFunctionRole.Arn

  TransformerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-FunctionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TransformerFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt TransformerFunction.Arn
  TransformerFunctionRole:
    Description: "Implicit IAM Role created for Lambda function"
    Value: !GetAtt TransformerFunctionRole.Arn
  SolutionId:
    Description: "Solution id"
    Value: "SO8150"
