name: "check issue"

on: issues

jobs:
  check-issue-compliance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Check issue compliance
      run: |
        echo "Issue title: ${{ github.event.issue.title }}"
        echo "${{ github.event.issue.body }}" > githubIssueBody.md
        ls
        vim githubIssueBody.md
#        python ./scripts/python/check_issue.py -b githubIssueBody.md

