name: "nodejs ci"

on:
  pull_request_target:
    types: [ labeled ]

jobs:
  nodejs-check-pr:
    if: startsWith(github.event.label.name, 'nodejs')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Check PR checkbox
      uses: JJ/github-pr-contains-action@releases/v2
      with:
        github-token: ${{github.token}}
        bodyContains: '[x]'
    - name: Check PR content
      run: |
        echo "${{ github.event.pull_request.body }}" > githubPRBody.md
        python ./scripts/python/check_pr.py -b githubPRBody.md

  nodejs-ci-precheck-content-scan:
    runs-on: ubuntu-latest
    needs: nodejs-check-pr
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CI }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CI }}
        aws-region: us-east-1
    - name: scan content
      run: |
        export labelName=${{ github.event.label.name }}
        ./scripts/nodejs-ci-content-scan.sh

  nodejs-ci-precheck-code-check:
    runs-on: ubuntu-latest
    needs: nodejs-ci-precheck-content-scan
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '12'               
    - name: check code style
      run: |
        export labelName=${{ github.event.label.name }}
        ./scripts/nodejs-ci-style-check.sh
    - name: build and code coverage
      run: |
        export labelName=${{ github.event.label.name }}
        ./scripts/nodejs-ci-build-coverage.sh        
      

  nodejs-ci-deploy-test:
    runs-on: ubuntu-latest
    needs: nodejs-ci-precheck-code-check
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CI }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CI }}
        aws-region: us-east-1
    - name: lambda@Edge test
      run: |
        export labelName=${{ github.event.label.name }}
        ./scripts/edge-test.sh

  nodejs-ci-add-label:
    runs-on: ubuntu-latest
    needs: nodejs-ci-deploy-test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}    
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: CI-Succeeded







