name: "nodejs ci"

on:
  pull_request:
    types: [ labeled ]

jobs:
  nodejs-check-pr:
    if: startsWith(github.event.label.name, 'nodejs')
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v2
      with:
        github-token: ${{github.token}}
        bodyContains: '[x]'

  nodejs-ci-precheck:
    runs-on: ubuntu-latest
    needs: nodejs-check-pr
    steps:
    - name: Checkout
      uses: actions/checkout@v2        
    - name: install jq
      run: sudo apt-get install jq 
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '12'  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: scan content
      run: |
        export labelName=${{ github.event.label.name }}
        ./scripts/nodejs-ci-content-scan.sh
    - name: check code style
      run: |
        export labelName=${{ github.event.label.name }}
        ./scripts/nodejs-ci-style-check.sh
    - name: build and code coverage
      run: |
        export labelName=${{ github.event.label.name }}
        ./scripts/nodejs-ci-build-coverage.sh      

  nodejs-ci-deploy-test:
    runs-on: ubuntu-latest
    needs: nodejs-ci-precheck
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: lambda@Edge test
      run: |
        export labelName=${{ github.event.label.name }}
        ./scripts/edge-test.sh

  nodejs-ci-add-label:
    runs-on: ubuntu-latest
    needs: nodejs-ci-deploy-test
    steps:
    - name: Checkout
      uses: actions/checkout@v2     
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: CI-Succeed                 







