name: "nodejs ci"

on:
  # TODO change to pull request 
  push:
    branches:
    - main
    # paths:
    # - 'edge/nodejs/nodejs.json'   

jobs:
  job1:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v2        
    - name: install jq
      run: sudo apt-get install jq 
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '12'             
    - name: run shell
      run: ./scripts/nodejs-ci-content-scan.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}        







