name: "python ci"

on:
  push:
    branches:
    - main
    paths:
    - 'edge/python/python.json'

jobs:
  python-ci-precheck:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v2        
    - name: Install JQ
      run: sudo apt-get install jq 
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: scan content
      run: ./scripts/python-ci-content-scan.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: check code style
      run: ./scripts/python-ci-style-check.sh  
    - name: Build and UT
      run: ./scripts/python-ci-build-ut.sh      

  python-ci-deploy-test:
    runs-on: ubuntu-latest
    needs: python-ci-precheck
    steps:
    - name: placeholder
      run: echo "TODO"