name: "Share apps"

on:
  # TODO change to pull request 
  push:
    branches:
    - main
    paths:
    - 'edge/share-apps.json'   

jobs:
  share-apps:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v2    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SAR }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SAR }}
        aws-region: us-east-1
    - name: Share apps 
      run: ./scripts/share-apps.sh



